#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width        3
bspc config window_gap          8

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle      true

# restore wallpaper
nitrogen --restore

# start lemonbar
killall bar.sh
${HOME}/.config/lemonbar/bar.sh&

# start dunst
killall dunst
sleep 0.5
dunst
